
export enum ActividadEnum {
  COTIZACION = 'COTIZACION',
  ACTUALIZACION = 'ACTUALIZACION'
}

export enum EstadoEnum {
    PENDIENTE = 'PENDIENTE',
    PROCESO = 'PROCESO',
    ENVIADO = 'ENVIADO',
    NO_COTIZAR = 'NO_COTIZAR',
    EN_PAUSA = 'EN_PAUSA'
}

export enum SistemaInicialEnum {
    PRELOSAS_BD = 'PRELOSAS_BD',
    PRELOSAS_ENTREPISOS = 'PRELOSAS_ENTREPISOS',
    VIGUETAS_PRETENSADAS = 'VIGUETAS_PRETENSADAS',
    LOSAS_ALVEOLARES = 'LOSAS_ALVEOLARES',
    PRELOSAS_PRETENSADAS = 'PRELOSAS_PRETENSADAS',
    CONVENCIONAL = 'CONVENCIONAL',
    ESPECIAL = 'ESPECIAL',
    LOSAS_POSTENSADAS = 'LOSAS_POSTENSADAS',
    REFERENCIAL = 'REFERENCIAL'
}
